# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{invoice_plugin}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2009-10-14}
  s.description = %q{Redmine plugin to create and manage invoices}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CREDITS.rdoc",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "TAGS",
     "VERSION",
     "app/controllers/invoice_controller.rb",
     "app/controllers/payments_controller.rb",
     "app/helpers/invoices_helper.rb",
     "app/models/autofill.rb",
     "app/models/invoice.rb",
     "app/models/payment.rb",
     "app/views/invoice/_form.rhtml",
     "app/views/invoice/_row.rhtml",
     "app/views/invoice/_table.rhtml",
     "app/views/invoice/autocreate.rhtml",
     "app/views/invoice/autofill.js.rjs",
     "app/views/invoice/edit.rhtml",
     "app/views/invoice/index.rhtml",
     "app/views/invoice/new.rhtml",
     "app/views/invoice/show.rhtml",
     "app/views/layouts/print.rhtml",
     "app/views/payments/_payment.html.erb",
     "app/views/payments/new.html.erb",
     "app/views/settings/_invoice_settings.rhtml",
     "assets/images/creditcards.png",
     "assets/images/money.png",
     "assets/images/money_add.png",
     "assets/images/printer.png",
     "assets/stylesheets/invoice.css",
     "assets/stylesheets/invoice_print.css",
     "config/locales/en.yml",
     "config/locales/fr.yml",
     "init.rb",
     "lang/en.yml",
     "lang/fr.yml",
     "lib/invoice_compatibility.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/TODO}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{invoice_plugin}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Redmine plugin to create and manage invoices}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
